### PR TITLE
BUG:  More cache logic fixes.

### PR DESCRIPTION
**Pull request by ntustison**

### CODE REVIEW

**Comment by cookpa** [comment]
Thanks @ntustison ! I dropped the ball on this refactoring once I figured out how to get the default dir mounted in Singularity.

**Comment by ntustison** [comment]
Oh, no worries.  Just, if you can, double check my thinking on this and I'll merge later.

**Comment by cookpa** [comment]
It works for me with a custom cache directory now.

**Comment by ntustison** [comment]
Awesome.  Thanks @cookpa

**Pull request merged**
